---

- hosts: webservers
  name: Our first Play

  vars_prompt:
    - name: username
      prompt: "enter username"
      private: no
    - name: lastname
      private: no
      prompt: "enter last name"
    - name: age
      private: no
      prompt: "enter age"

  vars:
    pkgname: nginx
    first_name: Mike
  
  tasks:

    - debug:
        msg: "{{ lastname }} is {{ age }} years old"

    - name: Task A
      debug:
        msg: Hello World
    - name: Task B
      debug:
        var: pkgname
    - name: Task C
      debug:
        msg: "Hello {{ first_name }}"



